# Generated by Django 5.1.6 on 2025-03-01 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Currency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=3, unique=True)),
                ("name", models.CharField(db_index=True, max_length=20)),
                ("symbol", models.CharField(max_length=10)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Provider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                ("priority", models.PositiveIntegerField(default=10)),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="smaller values have higher priority"
                    ),
                ),
            ],
            options={
                "ordering": ["priority"],
            },
        ),
        migrations.CreateModel(
            name="CurrencyExchangeRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("valuation_date", models.DateField(db_index=True)),
                (
                    "rate_value",
                    models.DecimalField(db_index=True, decimal_places=6, max_digits=18),
                ),
                (
                    "exchanged_currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.currency"
                    ),
                ),
                (
                    "source_currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exchanges",
                        to="app.currency",
                    ),
                ),
            ],
        ),
    ]
