# Generated by Django 5.1.6 on 2025-03-02 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="currencyexchangerate",
            options={"ordering": ["-valuation_date"]},
        ),
    ]
